name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16'

      - name: Build
        run: go build -v ./...

      - name: Deploy
        env:
          FIREBASE_CREDENTIALS_PATH: ${{ secrets.FIREBASE_CREDENTIALS_PATH }}
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
        run: |
          echo "$FIREBASE_CREDENTIALS_PATH" > /tmp/firebase_credentials.json
          export FIREBASE_CREDENTIALS_PATH=/tmp/firebase_credentials.json
          export GOOGLE_APPLICATION_CREDENTIALS=/tmp/firebase_credentials.json
          go run main.go
